/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppRouteRouteImport } from './routes/app/route'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as AppIndexRouteImport } from './routes/app/index'
import { Route as AppFinancesRouteRouteImport } from './routes/app/finances/route'
import { Route as AppGoalsRouteRouteImport } from './routes/app/goals/route'
import { Route as InformeDeviceIdRouteRouteImport } from './routes/informe/$deviceId/route'
import { Route as SignInSplatRouteImport } from './routes/sign-in.$'
import { Route as AppFinancesIndexRouteImport } from './routes/app/finances/index'
import { Route as AppGoalsIndexRouteImport } from './routes/app/goals/index'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRouteRoute = AppRouteRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppFinancesRouteRoute = AppFinancesRouteRouteImport.update({
  id: '/finances',
  path: '/finances',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppGoalsRouteRoute = AppGoalsRouteRouteImport.update({
  id: '/goals',
  path: '/goals',
  getParentRoute: () => AppRouteRoute,
} as any)
const InformeDeviceIdRouteRoute = InformeDeviceIdRouteRouteImport.update({
  id: '/informe/$deviceId',
  path: '/informe/$deviceId',
  getParentRoute: () => rootRouteImport,
} as any)
const SignInSplatRoute = SignInSplatRouteImport.update({
  id: '/sign-in/$',
  path: '/sign-in/$',
  getParentRoute: () => rootRouteImport,
} as any)
const AppFinancesIndexRoute = AppFinancesIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppFinancesRouteRoute,
} as any)
const AppGoalsIndexRoute = AppGoalsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppGoalsRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/app': typeof AppRouteRouteWithChildren
  '/onboarding': typeof OnboardingRoute
  '/app/finances': typeof AppFinancesRouteRouteWithChildren
  '/app/goals': typeof AppGoalsRouteRouteWithChildren
  '/informe/$deviceId': typeof InformeDeviceIdRouteRoute
  '/sign-in/$': typeof SignInSplatRoute
  '/app/': typeof AppIndexRoute
  '/app/finances/': typeof AppFinancesIndexRoute
  '/app/goals/': typeof AppGoalsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/onboarding': typeof OnboardingRoute
  '/informe/$deviceId': typeof InformeDeviceIdRouteRoute
  '/sign-in/$': typeof SignInSplatRoute
  '/app': typeof AppIndexRoute
  '/app/finances': typeof AppFinancesIndexRoute
  '/app/goals': typeof AppGoalsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/app': typeof AppRouteRouteWithChildren
  '/onboarding': typeof OnboardingRoute
  '/app/finances': typeof AppFinancesRouteRouteWithChildren
  '/app/goals': typeof AppGoalsRouteRouteWithChildren
  '/informe/$deviceId': typeof InformeDeviceIdRouteRoute
  '/sign-in/$': typeof SignInSplatRoute
  '/app/': typeof AppIndexRoute
  '/app/finances/': typeof AppFinancesIndexRoute
  '/app/goals/': typeof AppGoalsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/app'
    | '/onboarding'
    | '/app/finances'
    | '/app/goals'
    | '/informe/$deviceId'
    | '/sign-in/$'
    | '/app/'
    | '/app/finances/'
    | '/app/goals/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/onboarding'
    | '/informe/$deviceId'
    | '/sign-in/$'
    | '/app'
    | '/app/finances'
    | '/app/goals'
  id:
    | '__root__'
    | '/'
    | '/app'
    | '/onboarding'
    | '/app/finances'
    | '/app/goals'
    | '/informe/$deviceId'
    | '/sign-in/$'
    | '/app/'
    | '/app/finances/'
    | '/app/goals/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRouteRoute: typeof AppRouteRouteWithChildren
  OnboardingRoute: typeof OnboardingRoute
  InformeDeviceIdRouteRoute: typeof InformeDeviceIdRouteRoute
  SignInSplatRoute: typeof SignInSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/': {
      id: '/app/'
      path: '/'
      fullPath: '/app/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/finances': {
      id: '/app/finances'
      path: '/finances'
      fullPath: '/app/finances'
      preLoaderRoute: typeof AppFinancesRouteRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/goals': {
      id: '/app/goals'
      path: '/goals'
      fullPath: '/app/goals'
      preLoaderRoute: typeof AppGoalsRouteRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/informe/$deviceId': {
      id: '/informe/$deviceId'
      path: '/informe/$deviceId'
      fullPath: '/informe/$deviceId'
      preLoaderRoute: typeof InformeDeviceIdRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sign-in/$': {
      id: '/sign-in/$'
      path: '/sign-in/$'
      fullPath: '/sign-in/$'
      preLoaderRoute: typeof SignInSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/finances/': {
      id: '/app/finances/'
      path: '/'
      fullPath: '/app/finances/'
      preLoaderRoute: typeof AppFinancesIndexRouteImport
      parentRoute: typeof AppFinancesRouteRoute
    }
    '/app/goals/': {
      id: '/app/goals/'
      path: '/'
      fullPath: '/app/goals/'
      preLoaderRoute: typeof AppGoalsIndexRouteImport
      parentRoute: typeof AppGoalsRouteRoute
    }
  }
}

interface AppFinancesRouteRouteChildren {
  AppFinancesIndexRoute: typeof AppFinancesIndexRoute
}

const AppFinancesRouteRouteChildren: AppFinancesRouteRouteChildren = {
  AppFinancesIndexRoute: AppFinancesIndexRoute,
}

const AppFinancesRouteRouteWithChildren =
  AppFinancesRouteRoute._addFileChildren(AppFinancesRouteRouteChildren)

interface AppGoalsRouteRouteChildren {
  AppGoalsIndexRoute: typeof AppGoalsIndexRoute
}

const AppGoalsRouteRouteChildren: AppGoalsRouteRouteChildren = {
  AppGoalsIndexRoute: AppGoalsIndexRoute,
}

const AppGoalsRouteRouteWithChildren = AppGoalsRouteRoute._addFileChildren(
  AppGoalsRouteRouteChildren,
)

interface AppRouteRouteChildren {
  AppFinancesRouteRoute: typeof AppFinancesRouteRouteWithChildren
  AppGoalsRouteRoute: typeof AppGoalsRouteRouteWithChildren
  AppIndexRoute: typeof AppIndexRoute
}

const AppRouteRouteChildren: AppRouteRouteChildren = {
  AppFinancesRouteRoute: AppFinancesRouteRouteWithChildren,
  AppGoalsRouteRoute: AppGoalsRouteRouteWithChildren,
  AppIndexRoute: AppIndexRoute,
}

const AppRouteRouteWithChildren = AppRouteRoute._addFileChildren(
  AppRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRouteRoute: AppRouteRouteWithChildren,
  OnboardingRoute: OnboardingRoute,
  InformeDeviceIdRouteRoute: InformeDeviceIdRouteRoute,
  SignInSplatRoute: SignInSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
