const services = [
  ['Goal roadmap', 'Load objectives, current situation, and milestones to visualize progress over time.'],
  ['Decision impact preview', 'See whether a relevant purchase, installment plan, or extra expense moves a goal closer or farther away.'],
  ['Simple scenario simulation', 'Explore two or three possible paths without building a spreadsheet or chasing perfect forecasts.'],
  ['Installment visibility', 'Understand accumulated credit card installments and when they stop affecting the roadmap.'],
]

export function NorteLandingPage() {
  return (
    <>
      <a href="#main" className="sr-only focus:not-sr-only focus:fixed focus:left-4 focus:top-4 focus:z-50 focus:rounded-full focus:bg-[var(--sea-ink)] focus:px-4 focus:py-2 focus:text-[var(--on-primary)]">Skip to content</a>
      <main id="main">
        <section id="top" className="mx-auto grid max-w-6xl items-center gap-12 px-5 pb-20 pt-10 sm:px-8 lg:grid-cols-[1.05fr_0.95fr] lg:pb-28 lg:pt-16">
          <div><p className="mb-5 inline-flex rounded-full border border-[color-mix(in_oklab,var(--lagoon-deep)_25%,transparent)] bg-[var(--surface)] px-4 py-2 text-xs font-semibold uppercase tracking-[0.22em] text-[var(--lagoon-deep)]">Financial continuity system</p><h1 className="max-w-4xl text-5xl font-semibold tracking-[-0.05em] sm:text-6xl lg:text-7xl">Your financial north, before the decision.</h1><p className="mt-5 text-xl font-medium text-[var(--lagoon-deep)] sm:text-2xl">A financial continuity system for everyday choices.</p><p className="mt-7 max-w-2xl text-lg leading-8 text-[color-mix(in_oklab,var(--sea-ink)_78%,transparent)]">Norte helps you see whether everyday choices bring you closer to, or farther from, the goals you want to build. Not another expense tracker. A calm roadmap for deciding before it is too late.</p><p className="mt-4 max-w-2xl text-base leading-7 text-[color-mix(in_oklab,var(--sea-ink)_64%,transparent)]">Keep your plan alive as your income, expenses, installments, and priorities change.</p><div className="mt-9 flex flex-col gap-3 sm:flex-row"><a href="#soon" className="rounded-full bg-[var(--lagoon-deep)] px-6 py-3 text-center text-sm font-semibold uppercase tracking-[0.16em] text-[var(--on-primary)]">See what is coming</a><span className="rounded-full border border-[color-mix(in_oklab,var(--sea-ink)_20%,transparent)] bg-[var(--surface)] px-6 py-3 text-center text-sm font-semibold uppercase tracking-[0.16em] text-[var(--sea-ink)]">App links: Coming soon</span></div></div>
          <div className="mx-auto w-full max-w-[560px] overflow-hidden rounded-[2rem] bg-[color-mix(in_oklab,var(--on-primary)_30%,transparent)] p-2 shadow-[var(--shadow-card)] lg:max-w-none"><img src="/images/compass.jpg" alt="A hand holding a compass over an open road" className="h-[20rem] w-full rounded-[1.5rem] object-cover object-[35%_50%] sm:h-[28rem] lg:h-[34rem]" width="2048" height="1365" sizes="(min-width: 1024px) 48vw, (min-width: 640px) 560px, 100vw" /></div>
        </section>
        <section id="what" className="bg-[var(--sea-ink)] px-5 py-16 text-[var(--on-primary)] sm:px-8"><div className="mx-auto max-w-6xl"><p className="text-sm font-semibold uppercase tracking-[0.22em] text-[color-mix(in_oklab,var(--on-primary)_55%,transparent)]">What Norte does</p><h2 className="mt-4 max-w-3xl text-3xl font-semibold tracking-[-0.03em] sm:text-5xl">It keeps the link between present decisions and future goals alive.</h2><div className="mt-10 grid gap-4 md:grid-cols-3">{[['01', 'See the road ahead', 'Understand your current path and whether your habits are enough to reach each goal on time.'], ['02', 'Simulate alternatives', 'Compare simple paths: save more, delay a purchase, absorb an extra expense, or change pace.'], ['03', 'Decide without guilt', 'Norte is designed to accompany decisions without moralizing, blaming, or turning money into shame.']].map(([number, title, body]) => <article key={title} className="rounded-3xl border border-[color-mix(in_oklab,var(--on-primary)_10%,transparent)] bg-[color-mix(in_oklab,var(--on-primary)_7%,transparent)] p-6"><span className="text-sm font-semibold uppercase tracking-[0.2em] text-[var(--lagoon)]">{number}</span><h3 className="mt-5 text-xl font-semibold">{title}</h3><p className="mt-3 leading-7 text-[color-mix(in_oklab,var(--on-primary)_68%,transparent)]">{body}</p></article>)}</div></div></section>
        <section id="services" className="mx-auto max-w-6xl px-5 py-20 sm:px-8 lg:py-28"><div className="grid gap-10 lg:grid-cols-[0.8fr_1.2fr]"><div><p className="text-sm font-semibold uppercase tracking-[0.22em] text-[var(--lagoon-deep)]">Services</p><h2 className="mt-4 text-3xl font-semibold tracking-[-0.03em] sm:text-5xl">Built around goals, not categories.</h2><p className="mt-5 text-lg leading-8 text-[color-mix(in_oklab,var(--sea-ink)_68%,transparent)]">Traditional tools explain what already happened. Norte is being designed to show what a decision means for what you are trying to build.</p></div><div className="grid gap-4">{services.map(([title, body]) => <article key={title} className="route-card relative overflow-hidden rounded-3xl border border-[color-mix(in_oklab,var(--lagoon-deep)_18%,transparent)] bg-[var(--surface)] p-6 pl-14 shadow-[var(--shadow-card)]"><span className="absolute left-5 top-7 size-4 rounded-full bg-[var(--lagoon-deep)] ring-8 ring-[color-mix(in_oklab,var(--lagoon-deep)_10%,transparent)]" /><h3 className="text-xl font-semibold">{title}</h3><p className="mt-2 leading-7 text-[color-mix(in_oklab,var(--sea-ink)_68%,transparent)]">{body}</p></article>)}<article className="relative overflow-hidden rounded-3xl border border-[color-mix(in_oklab,var(--sea-ink)_15%,transparent)] bg-[var(--sea-ink)] p-6 pl-14 text-[var(--on-primary)] shadow-[var(--shadow-card)]"><span className="absolute left-5 top-7 size-4 rounded-full bg-[var(--sand)] ring-8 ring-[color-mix(in_oklab,var(--on-primary)_10%,transparent)]" /><h3 className="text-xl font-semibold">Low-friction tracking</h3><p className="mt-2 leading-7 text-[color-mix(in_oklab,var(--on-primary)_68%,transparent)]">Manual effort should be minimal. Automatic movement capture is part of the product roadmap as local infrastructure matures.</p></article></div></div></section>
        <section id="soon" className="px-5 pb-20 sm:px-8 lg:pb-28"><div className="mx-auto grid max-w-6xl gap-10 overflow-hidden rounded-[2rem] bg-[var(--lagoon-deep)] p-8 text-[var(--on-primary)] shadow-[var(--shadow-card)] sm:p-12 lg:grid-cols-[1fr_0.8fr] lg:items-end lg:p-16"><div><p className="text-sm font-semibold uppercase tracking-[0.22em] text-[color-mix(in_oklab,var(--on-primary)_60%,transparent)]">Coming soon</p><h2 className="mt-4 text-3xl font-semibold tracking-[-0.03em] sm:text-5xl">Norte is not available yet. We are building the first version.</h2><p className="mt-5 max-w-2xl text-lg leading-8 text-[color-mix(in_oklab,var(--on-primary)_72%,transparent)]">We are building an early version to help people make clearer financial decisions before they spend.</p></div><div className="grid gap-3 sm:grid-cols-2 lg:grid-cols-1">{['iOS app: Coming soon', 'Android app: Coming soon', 'Web access: Coming soon'].map((label) => <span key={label} className="rounded-2xl border border-[color-mix(in_oklab,var(--on-primary)_20%,transparent)] bg-[color-mix(in_oklab,var(--on-primary)_10%,transparent)] px-5 py-4 text-sm font-semibold uppercase tracking-[0.18em] text-[color-mix(in_oklab,var(--on-primary)_80%,transparent)]">{label}</span>)}</div></div></section>
      </main>
    </>
  )
}
