import { z } from 'zod'

export const reportSchema = z.object({
  meta: z.object({ nombre: z.string(), fecha: z.string(), alertas: z.number() }).strict(),
  apertura: z.object({ dolor_literal: z.string(), frase_apertura: z.string(), frase_sub: z.string() }).strict(),
  bloque1: z.object({
    ingreso_anual: z.number(),
    ingreso_anual_detalle: z.string(),
    pagar_anual: z.number(),
    pagar_anual_desc: z.string(),
    ajustable_anual: z.number(),
    ajustable_desc: z.string(),
    gastoN_concepto: z.string(),
    gastoN_mes_idx: z.number(),
    libre_anual_pre_tc: z.number(),
    tarjeta_anual: z.number(),
    ing_mensual: z.number(),
    texto_contexto: z.string(),
  }).strict(),
  bloque2: z.object({
    subtitulo: z.string(),
    P_monto: z.number(),
    P_pct: z.number(),
    V_monto: z.number(),
    V_pct: z.number(),
    D_monto: z.number(),
    D_pct: z.number(),
    margen_monto: z.number(),
    margen_pct: z.number(),
    comp_prox_mes: z.number(),
    arrastre: z.number().nullable(),
    interes_anual: z.number().nullable(),
    texto_analisis: z.string(),
  }).strict(),
  bloque3: z.object({
    colchon_objetivo: z.number(),
    escA_mes: z.string(),
    escA_fin18: z.number(),
    escB_mes: z.string(),
    escB_fin18: z.number(),
    escC_mes: z.string(),
    escC_fin18: z.number(),
    D_escB: z.number(),
    meses: z.array(z.string()),
    acum_A: z.array(z.number()),
    acum_C: z.array(z.number()),
    texto_hitos: z.string(),
  }).strict(),
  bloque4: z.object({
    titulo_gancho: z.string(),
    p1: z.string(),
    p2: z.string(),
    p3: z.string(),
    p4: z.string(),
    quote: z.string(),
    p5: z.string(),
    cta_label: z.string(),
    cta_confirm: z.string(),
    frase_cierre: z.string(),
  }).strict(),
}).strict()

export type Report = z.infer<typeof reportSchema>
